name: E2E Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
          cache: 'yarn'

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress Install
        uses: cypress-io/github-action@v4.2.0
        with:
          # Disable running of tests within install job
          runTests: false
          build: yarn install
      - name: Cypress Run E2E Tests
        uses: cypress-io/github-action@v4.2.0
        with:
          # we have already installed all dependencies above
          install: false
          start: yarn cy:run
          browser: chrome