name: E2E Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: yarn
      
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cypress Run E2E Tests
        uses: cypress-io/github-action@v4.2.0
        with:
          start: yarn cy:run
          browser: chrome